name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: rajbarath/flask-app:latest
      -
         name: Set up Terraform
         uses: hashicorp/setup-terraform@v1
         working-directory: ./terraform
         with:
           terraform_version: 0.13.0     
           
           id: Terraform Init
           run: terraform init
           
           id: Terraform Plan
           run: terraform plan 
           
           id: Terraform Apply
           run: terraform apply       
  
